### ISSUE TITLE
Incorrect attribution in energy consumption article

### ISSUE THREAD

**Issue by KevinMusgrave** [input-output-hk/essential-cardano-content#633]
The article titled [Comparison of energy consumption of Cardano and Bitcoin](https://github.com/input-output-hk/essential-cardano-content/blob/main/content/article/comparison-of-energy-consumption-of-cardano-and-bitcoin.md) says:

- "Peter Todd, a former Bitcoin core developer, has created a [tool that shows the security budget of Bitcoin](https://www.btcsecuritybudget.com/)"

This is incorrect. You can see who the actual creators are in the [btcsecuritybudget](https://github.com/creamofthecoin/btcsecuritybudget) git repo.

**Comment by olgahryniuk** [comment]
Thanks for raising this issue. Sorry that it took so long. This is now fixed.
